name: Build and Deploy BentoML Service

# Triggers the workflow on every push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    # Step 3: Install required Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bentoml scikit-learn pandas requests xgboost tqdm numpy

    # Step 4: Export models to BentoML
    - name: Export models to BentoML
      run: |
        # Export tfidf_model.bentomodel
        bentoml models import tfidf_model.bentomodel
        # Export xg_model.bentomodel
        bentoml models import xg_model.bentomodel
        
    # Step 4: Build BentoML service
    - name: BentoML Build
      run: |
        bentoml build

    # Step 5: Containerize BentoML service
    - name: BentoML Containerize
      run: |
        bentoml containerize score_xg_model:latest 

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker tag score_xg_model:latest ${{ secrets.DOCKER_USERNAME }}/score_xg_model:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/score_xg_model:latest

    - name: Run Docker container from Docker Hub
      run: |
        docker run --rm -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/score_xg_model:latest

    # Step 7: Wait for the Docker container to start
    - name: Wait for container startup
      run: |
        sleep 60

    # Step 8: Test the API using api_testing.py
    - name: Run API Tests
      run: |
        python api_testing.py
