name: Build and Deploy BentoML Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    # Step 3: Install required Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bentoml scikit-learn pandas requests xgboost tqdm numpy

    # Step 4: Export models to BentoML
    - name: Export models to BentoML
      run: |
        # Export tfidf_model.bentomodel
        bentoml models import tfidf_model.bentomodel
        # Export xg_model.bentomodel
        bentoml models import xg_model.bentomodel

    # Step 5: Build BentoML service
    - name: BentoML Build
      run: |
        bentoml build

    # Step 6: Containerize BentoML service and capture image name with tag
    - name: BentoML Containerize
      id: containerize
      run: |
        bentoml containerize score_xg_model:latest
        # Extract the generated image name and tag
        IMAGE_NAME="score_xg_model"
        IMAGE_TAG=$(docker images | grep "$IMAGE_NAME" | head -n 1 | awk '{print $1":"$2}')
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    # Step 7: Run the BentoML Docker container using the captured image name and tag
    - name: Run Docker container
      run: |
        docker run --rm -d -p 3000:3000 ${{ env.IMAGE_TAG }}

    # Step 8: Wait for the Docker container to start
    - name: Wait for container startup
      run: |
        sleep 10

    # Step 9: Test the API using api_testing.py
    - name: Run API Tests
      run: |
        python api_testing.py
