name: Build and Deploy BentoML Service

# Triggers the workflow on every push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    # Step 3: Install required Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bentoml scikit-learn pandas requests xgboost tqdm numpy

    # Step 4: Build BentoML service
    - name: BentoML Build
      run: |
        bentoml build

    # Step 5: Containerize BentoML service
    - name: BentoML Containerize
      run: |
        bentoml containerize score_xg_model:ngx4q7t67w4h5ygc 

    # Step 6: Run the BentoML Docker container on port 3000
    - name: Run Docker container
      run: |
        docker run --rm -p 3000:3000 score_xg_model:ngx4q7t67w4h5ygc

    # Step 7: Wait for the Docker container to start
    - name: Wait for container startup
      run: |
        sleep 10

    # Step 8: Test the API using api_testing.py
    - name: Run API Tests
      run: |
        python api_testing.py
